### ISSUE TITLE
Error using docker-machine and vmware fusion 7 pro

### ISSUE THREAD

**Issue by sly8787** [mblaschke/TYPO3-docker-boilerplate#104]
The initial startup of main fails.

```
docker containers <- (all=True, filters={u'label': [u'com.docker.compose.project=myprojectneos', u'com.docker.compose.service=storage', u'com.docker.compose.oneoff=False']})
docker containers -> (list with 1 items)
Creating myprojectneos_main_1...
docker create_container <- (name=u'myprojectneos_main_1', image=u'myprojectneos_main', labels={u'com.docker.compose.service': u'main', u'com.docker.compose.project': u'myprojectneos', 'com.docker.compose.config-hash': '66e56a8814ab8e908583ce5860709a76d564579a4daa55247826540b3b9f1e50', 'com.docker.compose.version': u'1.4.2', u'com.docker.compose.oneoff': u'False', 'com.docker.compose.container-number': '1'}, host_config={'Links': ['myprojectneos_mysql_1:myprojectneos_mysql_1', 'myprojectneos_mysql_1:mysql', 'myprojectneos_mysql_1:mysql_1'], 'PortBindings': {}, 'CapAdd': ['SYS_PTRACE'], 'Binds': [u'/Users/user/Projects/myproject.Neos:/docker:rw', u'/tmp/debug:/tmp/debug:rw'], 'ExtraHosts': [], 'LogConfig': {'Type': u'json-file', 'Config': {}}, 'Privileged': True, 'VolumesFrom': [u'eb5f0bd625ea144e3bdada9a90e57e3b72b745f21c69cb7149fb8c20eb66262d']}, environment={'MYSQL_PASSWORD': 'dev', 'FTP_USER': 'dev', 'CLI_USER': 'www-data', 'MYSQL_ROOT_PASSWORD': 'dev', 'EFFECTIVE_UID': '1000', 'POSTGRES_PASSWORD': 'dev', 'FLOW_REWRITEURLS': '1', 'TYPO3_CONTEXT': 'Development/Docker', 'PROVISION_CONTEXT': 'development', 'MYSQL_USER': 'dev', 'MAIL_GATEWAY': '192.168.56.2', 'PROVISION_PHP_XDEBUG': '1', 'SYMFONY_DEBUG': '0', 'SYMFONY_ENV': 'dev', 'POSTGRES_USER': 'dev', 'EFFECTIVE_GID': '1000', 'CLI_SCRIPT': 'php flow', 'FTP_PATH': '/data/ftp/', 'DNS_DOMAIN': 'vm vm.dev', 'FTP_PASSWORD': 'dev', 'MYSQL_DATABASE': 'typo3', 'FLOW_CONTEXT': 'Development/Docker', 'PROVISION_PHP_BLACKFIRE': '1', 'DOCUMENT_INDEX': 'index.php', 'DOCUMENT_ROOT': 'code/Web/'}, volumes={u'/docker': {}, u'/tmp/debug': {}}, detach=True)
docker create_container -> {u'Id': u'fbf9970cdd282d54b8201ea39a131b3d4f72b512a6d3271f8f84cfe632d5ca0a',
 u'Warnings': None}
docker inspect_container <- (u'fbf9970cdd282d54b8201ea39a131b3d4f72b512a6d3271f8f84cfe632d5ca0a')
docker inspect_container -> {u'AppArmorProfile': u'',
 u'Args': [u'supervisord'],
 u'Config': {u'AttachStderr': False,
             u'AttachStdin': False,
             u'AttachStdout': False,
             u'Cmd': [u'supervisord'],
             u'CpuShares': 0,
             u'Cpuset': u'',
             u'Domainname': u'',
             u'Entrypoint': [u'/entrypoint.sh'],
...
docker start <- (u'fbf9970cdd282d54b8201ea39a131b3d4f72b512a6d3271f8f84cfe632d5ca0a')
Cannot start container fbf9970cdd282d54b8201ea39a131b3d4f72b512a6d3271f8f84cfe632d5ca0a: [8] System error: no such file or directory
```

**Comment by mblaschke** [comment]
Windows or Mac?
Make sure you are able to use host mounted volumes (linux and macos: also make sure that your local docker boilerplate directory is shared with the same path as your host)

**Comment by sly8787** [comment]
I use Mac Yosemite 10.10.5 and these are my docker-compose settings.

```
#######################################
# Main php container
#######################################
main:
  build: docker/main
  #dockerfile: Ubuntu-12.04 # Ubuntu 12.04 - PHP 5.3, LTS (precise)
  dockerfile: Ubuntu-14.04  # Ubuntu 14.04 - PHP 5.5, LTS (trusty)
  #dockerfile: Ubuntu-15.04 # Ubuntu 15.04 - PHP 5.6 (vivid)
  #dockerfile: Ubuntu-15.10 # Ubuntu 15.10 - PHP 5.6 (wily)
  #dockerfile: Ubuntu-HHVM  # Ubuntu 14.04 - HHVM (trusty)
  #dockerfile: Centos-7     # CentOS 7     - PHP 5.4
  links:
    - mysql
    #- postgres
    #- mail
    #- solr
    #- elasticsearch
    #- redis
    #- memcached
    #- ftp
  volumes:
    - ./:/docker/
    - /tmp/debug/:/tmp/debug/
  volumes_from:
    - storage
  # cap and privileged needed for slowlog
  cap_add:
    - SYS_PTRACE
  privileged: true
  env_file:
    - docker-env.yml
```
