### ISSUE TITLE
Ghostscript should be available

### ISSUE THREAD

**Issue by josefglatz** [mblaschke/TYPO3-docker-boilerplate#145]
Otherwise TYPO3 can't read/write pdf and ai files.

**Comment by georgringer** [comment]
just until fixed

```
ct docker:root
apt-get update && apt-get install ghostscript -y
exit
```

**Comment by josefglatz** [comment]
### Another temporary workaround which survives a rebuild of your app container:

Add the following to _provision/roles/boilerplate-deployment/tasks/main.yml_:
```
- name: Update repositories cache and install "ghostscript" package
  apt:
    name: ghostscript
    update_cache: yes
```

off course you have to rebuild the app container
