### ISSUE TITLE
standalone web container + data proxy container

### ISSUE THREAD

**Issue by deminngi** [mblaschke/TYPO3-docker-boilerplate#94]
I love the docker idea to have portable container running everywhere.
I tried to implement an additional data proxy only container by delegating the
mount to the storeweb data container itself. That means in development mode
I point to ./code like you did, in production I have the data only inside the 
data container. Later on I would write a separate yml file for production to
reflect the difference.

```
storeweb:                
  build: docker/storage/
 volumes:                
    - /docker/code        
   # - ./code:/docker/code
```

inside the web container I changed the mount points as follow

```
web:                                      
  build: docker/web                       
  dockerfile: Apache-Httpd # Apache HTTPd 
  #dockerfile: Nginx       # Nginx        
  ports:                                  
    - 8000:80                             
    - 8443:443                            
  links:                                  
    - main                                
  volumes_from:                           
    # - main                                
    - storage
    - storeweb                             
  env_file:                               
    - docker-env.yml                      
```

Now I realized that you start the FPM port in main.
If I put a phpinfo.php file inside the storweb container in /docker/code
I get an Apache proxy error. 

I have some questions:
- Is there a chance to run or even use a FPM socket inside the web server if running
  standalone
- why do you start the FPM port on main and not inside web?

BTW I use the same procedure for db to route the database outside (only for development)

Is this a practicable solution for production or not?
