### ISSUE TITLE
Using alias for renaming containers

### ISSUE THREAD

**Issue by deminngi** [mblaschke/TYPO3-docker-boilerplate#95]
Hi succeded in changing the container names using my own. 
Here my findings:

```
mymain:                                                              
  build: docker/main                                                 
  #dockerfile: Ubuntu-12.04 # Ubuntu 12.04 - PHP 5.3, LTS (precise)  
  dockerfile: Ubuntu-14.04  # Ubuntu 14.04 - PHP 5.5, LTS (trusty)   
  #dockerfile: Ubuntu-15.04 # Ubuntu 15.04 - PHP 5.6 (vivid)         
  #dockerfile: Ubuntu-15.10 # Ubuntu 15.10 - PHP 5.6 (wily)          
  #dockerfile: Ubuntu-HHVM  # Ubuntu 14.04 - HHVM (trusty)           
  #dockerfile: Centos-7     # CentOS 7     - PHP 5.4                 
  container_name: mymain                                             
  hostname: mymain                                                   
  links:                                                             
    - mydb:mysql                                                   
    #- cmtpg                                                         
    #- cmtmail                                                       
    #- cmtsolr                                                       
    #- cmtsearch                                                     
    #- cmtredis                                                      
    #- cmtcache                                                      
    #- cmtftp                                                        
  volumes:                                                           
    #- ./:/docker/                                                    
    - /tmp/debug/:/tmp/debug/                                        
  volumes_from:                                                      
    - mystorage                                                        
  # cap and privileged needed for slowlog                            
  cap_add:                                                           
    - SYS_PTRACE                                                     
  privileged: true                                                   
  env_file:                                                          
    - docker-env.yml                                                 
```

the magic is behind links ...: of course Makefile targets must be aligned to :-)
